# Khithlainhtet - ShrutiBots API Stream URL Extractor & Cache Manager
# Optimized with API support, 500-limit Auto-Cache, and Fallback system

import os
import re
import aiohttp
import yt_dlp
import asyncio
from pathlib import Path
from datetime import datetime, timedelta
from collections import OrderedDict

from youtubesearchpython.future import Playlist, VideosSearch

from Newmusic import logger, config
from Newmusic.helpers import Track, utils

# --- SHRUTIBOTS API CONFIGURATION ---
API_URL = "https://api01.shrutibots.site"  # သို့မဟုတ် https://api.shrutibots.site / https://api01.shrutibots.site
API_KEY = "ShrutiBots7xhmAalRnTT0mTbgszR4"  # @ShrutiApibot မှ ထုတ်ယူထားသော သင်၏ Personal API Key ကို ဤနေရာတွင် ထည့်ပါ
# ------------------------------------

# --- COOKIE DATA START (Fallback အတွက်) ---
COOKIE_DATA = """# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor

.youtube.com	TRUE	/	TRUE	1788834227	VISITOR_PRIVACY_METADATA	CgJNTRIEGgAgZg%3D%3D
.youtube.com	TRUE	/	TRUE	1807842226	__Secure-3PSID	g.a0007gjBkEY2gKuIK-IDNA4O9IE8wiocn8xv3WOp-JbD6KKxZwXounGOWJraQeCKpqG-oSwq9wACgYKAZkSARISFQHGX2MizRsEjWIBfOf8FT3Y3LMa_RoVAUF8yKpOPp3cWUdYQ5Ao5O96IuJM0076
.youtube.com	TRUE	/	TRUE	1773283987	GPS	1
.youtube.com	TRUE	/	FALSE	1804818233	SIDCC	AKEyXzW1sqaKu6ScKuu9DKvRXkDOUkGb35L6HhIlYENKXlnQKqsd44MpPeDXCEVNXNiXMxq4
.youtube.com	TRUE	/	TRUE	1773368661	YSC	V5xhbUOi2aM
.youtube.com	TRUE	/	FALSE	1807842226	SID	g.a0007gjBkEY2gKuIK-IDNA4O9IE8wiocn8xv3WOp-JbD6KKxZwXoYEH2e75zTffKW0Xjy7JjNAACgYKAYYSARISFQHGX2Miw6hqbohoy53Wf7whYiki9xoVAUF8yKqy6CRK8cS9icqdLlHz7eND0076
.youtube.com	TRUE	/	TRUE	1804818226	__Secure-1PSIDTS	sidts-CjUBBj1CYnb_2un-x8U3DosdFcqPYVJhbg8Bk68ZCnIivIxZ-HGzJjNZhZ3mKsTTKPb9rfqcrxAA
.youtube.com	TRUE	/	TRUE	1773282831	CONSISTENCY	AG2Tqf8zG-huG-xjZAla2JPHKiMEKIrXDCYwlOHHGuhn4BqYzEQeeWHU4KBqrAnF4gXzuExsDwlRUzVRXKDOoYbqs5Cc2zhXioJl1PDof9f5T3qYUl27a9fnzomuUSXtDrxnp1hPZjCN1LI5o2cd_BCb
.youtube.com	TRUE	/	TRUE	1807842226	SAPISID	ool8aM3EyPScJD-Y/A2ZqSKUfmKB11OwXW
.youtube.com	TRUE	/	TRUE	1804818233	__Secure-1PSIDCC	AKEyXzWE3s3Z4jjWsZL2ADVxRV8QrrovXNLf3fLjfD9yjEGzPH3nS1nBe6mDRNa_Z19OZUfKZw
.youtube.com	TRUE	/	TRUE	1807842226	SSID	AT0hp-hXDaolbHwv7
.youtube.com	TRUE	/	TRUE	1807842226	__Secure-1PAPISID	ool8aM3EyPScJD-Y/A2ZqSKUfmKB11OwXW
.youtube.com	TRUE	/	TRUE	1807842226	__Secure-1PSID	g.a0007gjBkEY2gKuIK-IDNA4O9IE8wiocn8xv3WOp-JbD6KKxZwXo1xo64CJRyhnVfADBa2PqOgACgYKAV0SARISFQHGX2Mi1ad7QdhlGEysEgNracH2bhoVAUF8yKreHDECH5KvXV8UNvE31fIb0076
.youtube.com	TRUE	/	TRUE	1807842226	__Secure-3PAPISID	ool8aM3EyPScJD-Y/A2ZqSKUfmKB11OwXW
.youtube.com	TRUE	/	TRUE	1804818233	__Secure-3PSIDCC	AKEyXzUDsCV5ZzeaZ8_RRuemevoTvbJutsmPMlGkA6CmKMPY1zz4f5-mKS5HuYiYODFDpNNRRg
.youtube.com	TRUE	/	TRUE	1804818226	__Secure-3PSIDTS	sidts-CjUBBj1CYnb_2un-x8U3DosdFcqPYVJhbg8Bk68ZCnIivIxZ-HGzJjNZhZ3mKsTTKPb9rfqcrxAA
.youtube.com	TRUE	/	FALSE	1807842226	APISID	r2h8dJdwnPtOnB6w/A696rI3lpsRhDG7gE
.youtube.com	TRUE	/	FALSE	1807842226	HSID	AKFaV2VhVw1F0A1Ki
.youtube.com	TRUE	/	TRUE	1807842227	LOGIN_INFO	AFmmF2swRAIgcB7wcOs4WNVu-ntf7mqpZ0eDodNht4tOYj9GjX_22kcCIDZ6go5sU7AJYiXaiXvDo7RTNDux2DRqDwi5aMYf_6dA:QUQ3MjNmd2RNVmZwS2M4ajJCX0NDQTZRLUhZUERGOVU3ekR3UWpkZVZ3QXVwZ1JEWmM5cDExQWV4MzRzaXF5bS1uY0dFTUlDcDJySkVkd3pZbFRVc29uSEtKT0tscDRDOG93c3Zxd0R1ZkZCTlBYcGdqaFVzMWhhOTZaRWlwTDF6WDJWU0tiM3FmRW05dUlkMlVndFROblhyejBxeGc2a09R
.youtube.com	TRUE	/	TRUE	1807842230	PREF	tz=Asia.Rangoon&f7=100&f4=4000000
.youtube.com	TRUE	/	TRUE	1788834227	VISITOR_INFO1_LIVE	rQRaTxG5Dg8
"""
# --- COOKIE DATA END ---


class LimitedCache(OrderedDict):
    """အများဆုံး သီချင်း ၅၀၀ ပုဒ်ထိသာ Cache သိမ်းပေးပြီး ပြည့်သွားရင် အဟောင်းတွေကို အလိုအလျောက်ဖျက်ပေးသည်"""
    def __init__(self, maxsize=500, *args, **kwargs):
        self.maxsize = maxsize
        super().__init__(*args, **kwargs)

    def __setitem__(self, key, value):
        if key in self:
            self.move_to_end(key)
        super().__setitem__(key, value)
        if len(self) > self.maxsize:
            oldest = next(iter(self))
            del self[oldest]


class YouTube:
    def __init__(self):
        self.base = "https://www.youtube.com/watch?v="
        self.cookie_dir = "Newmusic/cookies"
        self.cookie_file = None
        
        # 500 ပုဒ် Limit ပါတဲ့ Cache စနစ်
        self.url_cache = LimitedCache(maxsize=500)       
        self.cache_ttl = 3600     # 1 hour cache TTL
        
        if not os.path.exists(self.cookie_dir):
            os.makedirs(self.cookie_dir)
        
        self.cookie_file = f"{self.cookie_dir}/youtube_cookies.txt"
        with open(self.cookie_file, "w", encoding="utf-8") as f:
            f.write(COOKIE_DATA)
        
        self.regex = re.compile(
            r"(https?://)?(www\.|m\.|music\.)?"
            r"(youtube\.com/(watch\?v=|shorts/|playlist\?list=)|youtu\.be/)"
            r"([A-Za-z0-9_-]{11}|PL[A-Za-z0-9_-]+)([&?][^\s]*)?"
        )
        self.iregex = re.compile(
            r"https?://(?:www\.|m\.|music\.)?(?:youtube\.com|youtu\.be)"
            r"(?!/(watch\?v=[A-Za-z0-9_-]{11}|shorts/[A-Za-z0-9_-]{11}"
            r"|playlist\?list=PL[A-Za-z0-9_-]+|[A-Za-z0-9_-]{11}))\S*"
        )
        
        logger.info("⚡ [Khithlainhtet] ShrutiBots API & 500-Limit Auto-Cache Mode Active")

    def get_cookies(self):
        if self.cookie_file and os.path.exists(self.cookie_file):
            return self.cookie_file
        return None

    async def save_cookies(self, urls: list[str]) -> None:
        pass

    def valid(self, url: str) -> bool:
        return bool(re.match(self.regex, url))

    def invalid(self, url: str) -> bool:
        return bool(re.match(self.iregex, url))

    # ---------------- SEARCH & PLAYLIST ----------------
    async def search(self, query: str, m_id: int, video: bool = False) -> Track | None:
        try:
            _search = VideosSearch(query, limit=1)
            results = await _search.next()
        except Exception:
            return None
        if results and results.get("result"):
            data = results["result"][0]
            return Track(
                id=data.get("id"),
                channel_name=data.get("channel", {}).get("name"),
                duration=data.get("duration"),
                duration_sec=utils.to_seconds(data.get("duration")),
                message_id=m_id,
                title=(data.get("title") or "")[:25],
                thumbnail=(data.get("thumbnails", [{}])[-1].get("url") or "").split("?")[0],
                url=data.get("link"),
                view_count=data.get("viewCount", {}).get("short"),
                video=video,
            )
        return None

    async def playlist(self, limit: int, user: str, url: str, video: bool) -> list[Track | None]:
        tracks = []
        try:
            plist = await Playlist.get(url)
            videos = plist.get("videos", []) or []

            while len(videos) < limit and plist.get("hasMoreVideos"):
                plist = await Playlist.getNextVideos(plist)
                if not plist:
                    break
                videos.extend(plist.get("videos", []) or [])

            for data in videos[:limit]:
                thumbs = data.get("thumbnails") or [{}]
                link = data.get("link") or f"{self.base}{data.get('id')}"
                track = Track(
                    id=data.get("id"),
                    channel_name=data.get("channel", {}).get("name", ""),
                    duration=data.get("duration"),
                    duration_sec=utils.to_seconds(data.get("duration")),
                    title=(data.get("title") or "")[:25],
                    thumbnail=(thumbs[-1].get("url") or "").split("?")[0],
                    url=link.split("&list=")[0],
                    user=user,
                    view_count="",
                    video=video,
                )
                tracks.append(track)
        except Exception:
            pass
        return tracks

    # ------------------- SHRUTIBOTS API STREAM URL EXTRACTOR -------------------
    async def get_stream_url(self, video_id: str, video: bool = False) -> str | None:
        """
        ShrutiBots API ကိုအသုံးပြု၍ Stream URL ထုတ်ယူခြင်း (API အလုပ်မလုပ်ပါက Cookie ဖြင့် yt_dlp သို့ Fallback လုပ်မည်)
        - type=audio သို့မဟုတ် type=video
        """
        media_type = "video" if video else "audio"
        
        # API_URL နှင့် API_KEY ထည့်ထားပါက API ကို ဦးစွာ သုံးမည်
        if API_URL and API_KEY:
            api_endpoint = f"{API_URL.rstrip('/')}/download?url={video_id}&type={media_type}&api_key={API_KEY}"
            try:
                async with aiohttp.ClientSession() as session:
                    async with session.get(api_endpoint, timeout=10) as response:
                        if response.status == 200:
                            data = await response.json()
                            # API မှပေးသော JSON ပုံစံပေါ်မူတည်၍ url ဖမ်းယူခြင်း (ဥပမာ: data['url'] သို့မဟုတ် data['link'])
                            stream_url = data.get("url") or data.get("link") or data.get("stream_url")
                            if stream_url:
                                return stream_url
            except Exception as e:
                logger.error(f"ShrutiBots API error for {video_id}: {e}, switching to fallback...")

        # --- Fallback: yt_dlp + Cookie (API မရတော့သည့်အခါ Bot ဆက်အလုပ်လုပ်ရန်) ---
        cookie = self.get_cookies()
        fmt = "best[height<=720][ext=mp4]/best[ext=mp4]/best" if video else "bestaudio[ext=webm][acodec=opus]/bestaudio[ext=m4a]/bestaudio"
        
        ydl_opts = {
            "quiet": True,
            "noplaylist": True,
            "geo_bypass": True,
            "no_warnings": True,
            "cookiefile": cookie,
            "format": fmt,
        }

        def _extract():
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                info = ydl.extract_info(self.base + video_id, download=False)
                return info['url']

        try:
            stream_url = await asyncio.to_thread(_extract)
            return stream_url
        except Exception as e:
            logger.error(f"Fallback extraction failed for {video_id}: {e}")
            return None

    # ------------------- CACHED VERSION (500-LIMIT LRU) -------------------
    async def get_stream_url_cached(self, video_id: str, video: bool = False) -> str | None:
        """Cache စစ်ဆေးခြင်း (အများဆုံး ၅၀၀ ပုဒ်ထိ မှတ်မည်)"""
        now = datetime.now()
        key = f"{video_id}_{video}"
        
        if key in self.url_cache:
            url, expires = self.url_cache[key]
            if now < expires:
                self.url_cache.move_to_end(key)
                return url

        url = await self.get_stream_url(video_id, video)
        if url:
            self.url_cache[key] = (url, now + timedelta(seconds=self.cache_ttl))
        return url

    # ------------------- COMPATIBILITY METHOD -------------------
    async def download(self, video_id: str, video: bool = False) -> str | None:
        """Compatibility method for existing bot code"""
        return await self.get_stream_url_cached(video_id, video)
